name: Train S&P 500 Models via SageMaker

on:
  workflow_dispatch:

jobs:
  train-sagemaker:
    runs-on: ubuntu-latest
    environment: prod-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload training script and requirements to S3
        run: |
          aws s3 cp ml/train_model.py s3://${{ vars.MODEL_BUCKET_NAME }}/scripts/train_model.py
          aws s3 cp ml/requirements.txt s3://${{ vars.MODEL_BUCKET_NAME }}/scripts/requirements.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Trigger SageMaker training job
        run: |
          aws sagemaker create-training-job \
            --region us-east-1 \
            --training-job-name sp500-train-${{ github.run_id }} \
            --algorithm-specification TrainingImage=896924684176.dkr.ecr.us-east-1.amazonaws.com/stock-analyzer-shrubb-ai-custom-trainer:${{ vars.TRAIN_IMAGE_VERSION }},TrainingInputMode=File \
            --input-data-config '[]' \
            --output-data-config S3OutputPath=s3://${{ vars.MODEL_BUCKET_NAME }}/models/ \
            --resource-config InstanceType=ml.m5.large,InstanceCount=1,VolumeSizeInGB=10 \
            --stopping-condition MaxRuntimeInSeconds=3000 \
            --role-arn arn:aws:iam::896924684176:role/shrubb-ai-sagemaker-execution-role
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
